using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MagentoIntegrationApp.Models
{
    public class Customer
    {
    }
}


//public class Order
//{
//    public int adjustment_negative { get; set; }
//    public int adjustment_positive { get; set; }
//    public string applied_rule_ids { get; set; }
//    public int base_adjustment_negative { get; set; }
//    public int base_adjustment_positive { get; set; }
//    public string base_currency_code { get; set; }
//    public double base_discount_amount { get; set; }
//    public double base_discount_canceled { get; set; }
//    public double base_discount_invoiced { get; set; }
//    public double base_discount_refunded { get; set; }
//    public double base_grand_total { get; set; }
//    public double base_discount_tax_compensation_amount { get; set; }
//    public double base_discount_tax_compensation_invoiced { get; set; }
//    public double base_discount_tax_compensation_refunded { get; set; }
//    public double base_shipping_amount { get; set; }
//    public double base_shipping_canceled { get; set; }
//    public double base_shipping_discount_amount { get; set; }
//    public double base_shipping_discount_tax_compensation_amnt { get; set; }
//    public double base_shipping_incl_tax { get; set; }
//    public double base_shipping_invoiced { get; set; }
//    public double base_shipping_refunded { get; set; }
//    public double base_shipping_tax_amount { get; set; }
//    public double base_shipping_tax_refunded { get; set; }
//    public double base_subtotal { get; set; }
//    public double base_subtotal_canceled { get; set; }
//    public double base_subtotal_incl_tax { get; set; }
//    public double base_subtotal_invoiced { get; set; }
//    public double base_subtotal_refunded { get; set; }
//    public double base_tax_amount { get; set; }
//    public double base_tax_canceled { get; set; }
//    public double base_tax_invoiced { get; set; }
//    public double base_tax_refunded { get; set; }
//    public double base_total_canceled { get; set; }
//    public double base_total_due { get; set; }
//    public double base_total_invoiced { get; set; }
//    public double base_total_invoiced_cost { get; set; }
//    public double base_total_offline_refunded { get; set; }
//    public double base_total_online_refunded { get; set; }
//    public double base_total_paid { get; set; }
//    public int base_total_qty_ordered { get; set; }
//    public double base_total_refunded { get; set; }
//    public int base_to_global_rate { get; set; }
//    public int base_to_order_rate { get; set; }
//    public int billing_address_id { get; set; }
//    public int can_ship_partially { get; set; }
//    public int can_ship_partially_item { get; set; }
//    public string coupon_code { get; set; }
//    public string created_at { get; set; }
//    public string customer_dob { get; set; }
//    public string customer_email { get; set; }
//    public string customer_firstname { get; set; }
//    public int customer_gender { get; set; }
//    public int customer_group_id { get; set; }
//    public int customer_id { get; set; }
//    public int customer_is_guest { get; set; }
//    public string customer_lastname { get; set; }
//    public string customer_middlename { get; set; }
//    public string customer_note { get; set; }
//    public int customer_note_notify { get; set; }
//    public string customer_prefix { get; set; }
//    public string customer_suffix { get; set; }
//    public string customer_taxvat { get; set; }
//    public double discount_amount { get; set; }
//    public double discount_canceled { get; set; }
//    public string discount_description { get; set; }
//    public double discount_invoiced { get; set; }
//    public double discount_refunded { get; set; }
//    public int edit_increment { get; set; }
//    public int email_sent { get; set; }
//    public int entity_id { get; set; }
//    public string ext_customer_id { get; set; }
//    public string ext_order_id { get; set; }
//    public int forced_shipment_with_invoice { get; set; }
//    public string global_currency_code { get; set; }
//    public double grand_total { get; set; }
//    public double discount_tax_compensation_amount { get; set; }
//    public double discount_tax_compensation_invoiced { get; set; }
//    public double discount_tax_compensation_refunded { get; set; }
//    public string hold_before_state { get; set; }
//    public string hold_before_status { get; set; }
//    public string increment_id { get; set; }
//    public int is_virtual { get; set; }
//    public string order_currency_code { get; set; }
//    public string original_increment_id { get; set; }
//    public double payment_authorization_amount { get; set; }
//    public int payment_auth_expiration { get; set; }
//    public string protect_code { get; set; }
//    public int quote_address_id { get; set; }
//    public int quote_id { get; set; }
//    public string relation_child_id { get; set; }
//    public string relation_child_real_id { get; set; }
//    public string relation_parent_id { get; set; }
//    public string relation_parent_real_id { get; set; }
//    public string remote_ip { get; set; }
//    public double shipping_amount { get; set; }
//    public double shipping_canceled { get; set; }
//    public string shipping_description { get; set; }
//    public double shipping_discount_amount { get; set; }
//    public double shipping_discount_tax_compensation_amount { get; set; }
//    public double shipping_incl_tax { get; set; }
//    public double shipping_invoiced { get; set; }
//    public double shipping_refunded { get; set; }
//    public double shipping_tax_amount { get; set; }
//    public double shipping_tax_refunded { get; set; }
//    public string state { get; set; }
//    public string status { get; set; }
//    public string store_currency_code { get; set; }
//    public int store_id { get; set; }
//    public string store_name { get; set; }
//    public int store_to_base_rate { get; set; }
//    public int store_to_order_rate { get; set; }
//    public double subtotal { get; set; }
//    public double subtotal_canceled { get; set; }
//    public double subtotal_incl_tax { get; set; }
//    public double subtotal_invoiced { get; set; }
//    public double subtotal_refunded { get; set; }
//    public double tax_amount { get; set; }
//    public double tax_canceled { get; set; }
//    public double tax_invoiced { get; set; }
//    public double tax_refunded { get; set; }
//    public double total_canceled { get; set; }
//    public double total_due { get; set; }
//    public double total_invoiced { get; set; }
//    public double total_item_count { get; set; }
//    public double total_offline_refunded { get; set; }
//    public double total_online_refunded { get; set; }
//    public double total_paid { get; set; }
//    public double total_qty_ordered { get; set; }
//    public double total_refunded { get; set; }
//    public string updated_at { get; set; }
//    public double weight { get; set; }
//    public string x_forwarded_for { get; set; }
//    public List<Item2> items { get; set; }
//    public BillingAddress billing_address { get; set; }
//    public Payment payment { get; set; }
//    public List<StatusHistory> status_histories { get; set; }
//    public ExtensionAttributes11 extension_attributes { get; set; }
//}

//public class Item2
//{
//    public string additional_data { get; set; }
//    public double amount_refunded { get; set; }
//    public string applied_rule_ids { get; set; }
//    public double base_amount_refunded { get; set; }
//    public double base_cost { get; set; }
//    public double base_discount_amount { get; set; }
//    public double base_discount_invoiced { get; set; }
//    public double base_discount_refunded { get; set; }
//    public double base_discount_tax_compensation_amount { get; set; }
//    public double base_discount_tax_compensation_invoiced { get; set; }
//    public double base_discount_tax_compensation_refunded { get; set; }
//    public double base_original_price { get; set; }
//    public double base_price { get; set; }
//    public double base_price_incl_tax { get; set; }
//    public double base_row_invoiced { get; set; }
//    public double base_row_total { get; set; }
//    public double base_row_total_incl_tax { get; set; }
//    public double base_tax_amount { get; set; }
//    public double base_tax_before_discount { get; set; }
//    public double base_tax_invoiced { get; set; }
//    public double base_tax_refunded { get; set; }
//    public double base_weee_tax_applied_amount { get; set; }
//    public double base_weee_tax_applied_row_amnt { get; set; }
//    public double base_weee_tax_disposition { get; set; }
//    public double base_weee_tax_row_disposition { get; set; }
//    public string created_at { get; set; }
//    public string description { get; set; }
//    public double discount_amount { get; set; }
//    public double discount_invoiced { get; set; }
//    public double discount_percent { get; set; }
//    public double discount_refunded { get; set; }
//    public double event_id { get; set; }
//    public string ext_order_item_id { get; set; }
//    public double free_shipping { get; set; }
//    public double gw_base_price { get; set; }
//    public double gw_base_price_invoiced { get; set; }
//    public double gw_base_price_refunded { get; set; }
//    public double gw_base_tax_amount { get; set; }
//    public double gw_base_tax_amount_invoiced { get; set; }
//    public double gw_base_tax_amount_refunded { get; set; }
//    public int gw_id { get; set; }
//    public double gw_price { get; set; }
//    public double gw_price_invoiced { get; set; }
//    public double gw_price_refunded { get; set; }
//    public double gw_tax_amount { get; set; }
//    public double gw_tax_amount_invoiced { get; set; }
//    public double gw_tax_amount_refunded { get; set; }
//    public double discount_tax_compensation_amount { get; set; }
//    public double discount_tax_compensation_canceled { get; set; }
//    public double discount_tax_compensation_invoiced { get; set; }
//    public double discount_tax_compensation_refunded { get; set; }
//    public int is_qty_decimal { get; set; }
//    public int is_virtual { get; set; }
//    public int item_id { get; set; }
//    public int locked_do_invoice { get; set; }
//    public int locked_do_ship { get; set; }
//    public string name { get; set; }
//    public double no_discount { get; set; }
//    public int order_id { get; set; }
//    public double original_price { get; set; }
//    public int parent_item_id { get; set; }
//    public double price { get; set; }
//    public double price_incl_tax { get; set; }
//    public int product_id { get; set; }
//    public string product_type { get; set; }
//    public int qty_backordered { get; set; }
//    public int qty_canceled { get; set; }
//    public int qty_invoiced { get; set; }
//    public int qty_ordered { get; set; }
//    public int qty_refunded { get; set; }
//    public int qty_returned { get; set; }
//    public int qty_shipped { get; set; }
//    public int quote_item_id { get; set; }
//    public int row_invoiced { get; set; }
//    public double row_total { get; set; }
//    public double row_total_incl_tax { get; set; }
//    public double row_weight { get; set; }
//    public string sku { get; set; }
//    public int store_id { get; set; }
//    public double tax_amount { get; set; }
//    public double tax_before_discount { get; set; }
//    public double tax_canceled { get; set; }
//    public double tax_invoiced { get; set; }
//    public double tax_percent { get; set; }
//    public double tax_refunded { get; set; }
//    public string updated_at { get; set; }
//    public string weee_tax_applied { get; set; }
//    public double weee_tax_applied_amount { get; set; }
//    public double weee_tax_applied_row_amount { get; set; }
//    public double weee_tax_disposition { get; set; }
//    public double weee_tax_row_disposition { get; set; }
//    public double weight { get; set; }
//    public ParentItem parent_item { get; set; }
//    public ProductOption product_option { get; set; }
//    public ExtensionAttributes6 extension_attributes { get; set; }
//}
//public class BillingAddress
//{
//    public string address_type { get; set; }
//    public string city { get; set; }
//    public string company { get; set; }
//    public string country_id { get; set; }
//    public int customer_address_id { get; set; }
//    public int customer_id { get; set; }
//    public string email { get; set; }
//    public int entity_id { get; set; }
//    public string fax { get; set; }
//    public string firstname { get; set; }
//    public string lastname { get; set; }
//    public string middlename { get; set; }
//    public int parent_id { get; set; }
//    public string postcode { get; set; }
//    public string prefix { get; set; }
//    public string region { get; set; }
//    public string region_code { get; set; }
//    public int region_id { get; set; }
//    public List<string> street { get; set; }
//    public string suffix { get; set; }
//    public string telephone { get; set; }
//    public string vat_id { get; set; }
//    public int vat_is_valid { get; set; }
//    public string vat_request_date { get; set; }
//    public string vat_request_id { get; set; }
//    public int vat_request_success { get; set; }
//    public ExtensionAttributes8 extension_attributes { get; set; }
//}
//public class Payment
//{
//    public string account_status { get; set; }
//    public string additional_data { get; set; }
//    public List<string> additional_information { get; set; }
//    public string address_status { get; set; }
//    public double amount_authorized { get; set; }
//    public double amount_canceled { get; set; }
//    public double amount_ordered { get; set; }
//    public double amount_paid { get; set; }
//    public double amount_refunded { get; set; }
//    public string anet_trans_method { get; set; }
//    public double base_amount_authorized { get; set; }
//    public double base_amount_canceled { get; set; }
//    public double base_amount_ordered { get; set; }
//    public double base_amount_paid { get; set; }
//    public double base_amount_paid_online { get; set; }
//    public double base_amount_refunded { get; set; }
//    public double base_amount_refunded_online { get; set; }
//    public double base_shipping_amount { get; set; }
//    public double base_shipping_captured { get; set; }
//    public double base_shipping_refunded { get; set; }
//    public string cc_approval { get; set; }
//    public string cc_avs_status { get; set; }
//    public string cc_cid_status { get; set; }
//    public string cc_debug_request_body { get; set; }
//    public string cc_debug_response_body { get; set; }
//    public string cc_debug_response_serialized { get; set; }
//    public string cc_exp_month { get; set; }
//    public string cc_exp_year { get; set; }
//    public string cc_last4 { get; set; }
//    public string cc_number_enc { get; set; }
//    public string cc_owner { get; set; }
//    public string cc_secure_verify { get; set; }
//    public string cc_ss_issue { get; set; }
//    public string cc_ss_start_month { get; set; }
//    public string cc_ss_start_year { get; set; }
//    public string cc_status { get; set; }
//    public string cc_status_description { get; set; }
//    public string cc_trans_id { get; set; }
//    public string cc_type { get; set; }
//    public string echeck_account_name { get; set; }
//    public string echeck_account_type { get; set; }
//    public string echeck_bank_name { get; set; }
//    public string echeck_routing_number { get; set; }
//    public string echeck_type { get; set; }
//    public int entity_id { get; set; }
//    public string last_trans_id { get; set; }
//    public string method { get; set; }
//    public int parent_id { get; set; }
//    public string po_number { get; set; }
//    public string protection_eligibility { get; set; }
//    public int quote_payment_id { get; set; }
//    public double shipping_amount { get; set; }
//    public double shipping_captured { get; set; }
//    public double shipping_refunded { get; set; }
//    public ExtensionAttributes9 extension_attributes { get; set; }
//}
//public class StatusHistory
//{
//    public string comment { get; set; }
//    public string created_at { get; set; }
//    public int entity_id { get; set; }
//    public string entity_name { get; set; }
//    public int is_customer_notified { get; set; }
//    public int is_visible_on_front { get; set; }
//    public int parent_id { get; set; }
//    public string status { get; set; }
//    public ExtensionAttributes10 extension_attributes { get; set; }
//}

//public class ExtensionAttributes11
//{
//    public List<ShippingAssignment> shipping_assignments { get; set; }
//    public List<AppliedTax> applied_taxes { get; set; }
//    public List<ItemAppliedTax> item_applied_taxes { get; set; }
//    public bool converting_from_quote { get; set; }
//    public CompanyOrderAttributes company_order_attributes { get; set; }
//    public double base_customer_balance_amount { get; set; }
//    public double customer_balance_amount { get; set; }
//    public double base_customer_balance_invoiced { get; set; }
//    public double customer_balance_invoiced { get; set; }
//    public double base_customer_balance_refunded { get; set; }
//    public double customer_balance_refunded { get; set; }
//    public double base_customer_balance_total_refunded { get; set; }
//    public double customer_balance_total_refunded { get; set; }
//    public List<GiftCard> gift_cards { get; set; }
//    public double base_gift_cards_amount { get; set; }
//    public double gift_cards_amount { get; set; }
//    public int base_gift_cards_invoiced { get; set; }
//    public int gift_cards_invoiced { get; set; }
//    public int base_gift_cards_refunded { get; set; }
//    public int gift_cards_refunded { get; set; }
//    public GiftMessage3 gift_message { get; set; }
//    public string gw_id { get; set; }
//    public string gw_allow_gift_receipt { get; set; }
//    public string gw_add_card { get; set; }
//    public string gw_base_price { get; set; }
//    public string gw_price { get; set; }
//    public string gw_items_base_price { get; set; }
//    public string gw_items_price { get; set; }
//    public string gw_card_base_price { get; set; }
//    public string gw_card_price { get; set; }
//    public string gw_base_tax_amount { get; set; }
//    public string gw_tax_amount { get; set; }
//    public string gw_items_base_tax_amount { get; set; }
//    public string gw_items_tax_amount { get; set; }
//    public string gw_card_base_tax_amount { get; set; }
//    public string gw_card_tax_amount { get; set; }
//    public string gw_base_price_incl_tax { get; set; }
//    public string gw_price_incl_tax { get; set; }
//    public string gw_items_base_price_incl_tax { get; set; }
//    public string gw_items_price_incl_tax { get; set; }
//    public string gw_card_base_price_incl_tax { get; set; }
//    public string gw_card_price_incl_tax { get; set; }
//    public string gw_base_price_invoiced { get; set; }
//    public string gw_price_invoiced { get; set; }
//    public string gw_items_base_price_invoiced { get; set; }
//    public string gw_items_price_invoiced { get; set; }
//    public string gw_card_base_price_invoiced { get; set; }
//    public string gw_card_price_invoiced { get; set; }
//    public string gw_base_tax_amount_invoiced { get; set; }
//    public string gw_tax_amount_invoiced { get; set; }
//    public string gw_items_base_tax_invoiced { get; set; }
//    public string gw_items_tax_invoiced { get; set; }
//    public string gw_card_base_tax_invoiced { get; set; }
//    public string gw_card_tax_invoiced { get; set; }
//    public string gw_base_price_refunded { get; set; }
//    public string gw_price_refunded { get; set; }
//    public string gw_items_base_price_refunded { get; set; }
//    public string gw_items_price_refunded { get; set; }
//    public string gw_card_base_price_refunded { get; set; }
//    public string gw_card_price_refunded { get; set; }
//    public string gw_base_tax_amount_refunded { get; set; }
//    public string gw_tax_amount_refunded { get; set; }
//    public string gw_items_base_tax_refunded { get; set; }
//    public string gw_items_tax_refunded { get; set; }
//    public string gw_card_base_tax_refunded { get; set; }
//    public string gw_card_tax_refunded { get; set; }
//}
